import type { SupportedLanguage, BibleTranslation } from '../types';

// ============================================================================
// SUPPORTED LANGUAGES
// ============================================================================

export const LANGUAGES: Record<SupportedLanguage, { name: string; nativeName: string; dir: 'ltr' | 'rtl' }> = {
  en: { name: 'English', nativeName: 'English', dir: 'ltr' },
  ja: { name: 'Japanese', nativeName: '日本語', dir: 'ltr' },
  es: { name: 'Spanish', nativeName: 'Español', dir: 'ltr' },
};

// ============================================================================
// BIBLE TRANSLATIONS
// ============================================================================

export const AVAILABLE_TRANSLATIONS: Omit<BibleTranslation, 'isDownloaded' | 'lastSynced'>[] = [
  // English
  {
    id: 'niv',
    name: 'New International Version',
    abbreviation: 'NIV',
    language: 'en',
    copyright: '© Biblica',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'esv',
    name: 'English Standard Version',
    abbreviation: 'ESV',
    language: 'en',
    copyright: '© Crossway',
    bookCount: 66,
    verseCount: 31086,
  },
  {
    id: 'kjv',
    name: 'King James Version',
    abbreviation: 'KJV',
    language: 'en',
    copyright: 'Public Domain',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'asv',
    name: 'American Standard Version',
    abbreviation: 'ASV',
    language: 'en',
    copyright: 'Public Domain',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'bbe',
    name: 'Bible in Basic English',
    abbreviation: 'BBE',
    language: 'en',
    copyright: 'Public Domain',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'nkjv',
    name: 'New King James Version',
    abbreviation: 'NKJV',
    language: 'en',
    copyright: '© Thomas Nelson',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'nlt',
    name: 'New Living Translation',
    abbreviation: 'NLT',
    language: 'en',
    copyright: '© Tyndale House',
    bookCount: 66,
    verseCount: 31086,
  },
  // Japanese
  {
    id: 'jlb',
    name: 'Japanese Living Bible',
    abbreviation: 'JLB',
    language: 'ja',
    copyright: '© Biblica',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'kougo',
    name: '口語訳聖書',
    abbreviation: '口語訳',
    language: 'ja',
    copyright: 'Public Domain',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'japkougo',
    name: '口語訳聖書 (Kougo-yaku)',
    abbreviation: '口語訳',
    language: 'ja',
    copyright: 'Public Domain',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'japbungo',
    name: '明治元訳/大正改訳',
    abbreviation: '文語訳',
    language: 'ja',
    copyright: 'Public Domain',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'shinkaiyaku',
    name: '新改訳聖書',
    abbreviation: '新改訳',
    language: 'ja',
    copyright: '© 新日本聖書刊行会',
    bookCount: 66,
    verseCount: 31102,
  },
  // Spanish
  {
    id: 'rvr1960',
    name: 'Reina-Valera 1960',
    abbreviation: 'RVR1960',
    language: 'es',
    copyright: '© Sociedades Bíblicas Unidas',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'rvr1909',
    name: 'Reina-Valera 1909',
    abbreviation: 'RVR1909',
    language: 'es',
    copyright: 'Public Domain',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'rvr1865',
    name: 'Reina-Valera 1865',
    abbreviation: 'RVR1865',
    language: 'es',
    copyright: 'Public Domain',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'nvi',
    name: 'Nueva Versión Internacional',
    abbreviation: 'NVI',
    language: 'es',
    copyright: '© Biblica',
    bookCount: 66,
    verseCount: 31102,
  },
  {
    id: 'lbla',
    name: 'La Biblia de las Américas',
    abbreviation: 'LBLA',
    language: 'es',
    copyright: '© The Lockman Foundation',
    bookCount: 66,
    verseCount: 31102,
  },
];

// ============================================================================
// BIBLE BOOKS
// ============================================================================

export const BIBLE_BOOKS = {
  en: [
    // Old Testament
    { abbrev: 'Gen', name: 'Genesis', chapters: 50 },
    { abbrev: 'Exod', name: 'Exodus', chapters: 40 },
    { abbrev: 'Lev', name: 'Leviticus', chapters: 27 },
    { abbrev: 'Num', name: 'Numbers', chapters: 36 },
    { abbrev: 'Deut', name: 'Deuteronomy', chapters: 34 },
    { abbrev: 'Josh', name: 'Joshua', chapters: 24 },
    { abbrev: 'Judg', name: 'Judges', chapters: 21 },
    { abbrev: 'Ruth', name: 'Ruth', chapters: 4 },
    { abbrev: '1Sam', name: '1 Samuel', chapters: 31 },
    { abbrev: '2Sam', name: '2 Samuel', chapters: 24 },
    { abbrev: '1Kgs', name: '1 Kings', chapters: 22 },
    { abbrev: '2Kgs', name: '2 Kings', chapters: 25 },
    { abbrev: '1Chr', name: '1 Chronicles', chapters: 29 },
    { abbrev: '2Chr', name: '2 Chronicles', chapters: 36 },
    { abbrev: 'Ezra', name: 'Ezra', chapters: 10 },
    { abbrev: 'Neh', name: 'Nehemiah', chapters: 13 },
    { abbrev: 'Esth', name: 'Esther', chapters: 10 },
    { abbrev: 'Job', name: 'Job', chapters: 42 },
    { abbrev: 'Ps', name: 'Psalms', chapters: 150 },
    { abbrev: 'Prov', name: 'Proverbs', chapters: 31 },
    { abbrev: 'Eccl', name: 'Ecclesiastes', chapters: 12 },
    { abbrev: 'Song', name: 'Song of Solomon', chapters: 8 },
    { abbrev: 'Isa', name: 'Isaiah', chapters: 66 },
    { abbrev: 'Jer', name: 'Jeremiah', chapters: 52 },
    { abbrev: 'Lam', name: 'Lamentations', chapters: 5 },
    { abbrev: 'Ezek', name: 'Ezekiel', chapters: 48 },
    { abbrev: 'Dan', name: 'Daniel', chapters: 12 },
    { abbrev: 'Hos', name: 'Hosea', chapters: 14 },
    { abbrev: 'Joel', name: 'Joel', chapters: 3 },
    { abbrev: 'Amos', name: 'Amos', chapters: 9 },
    { abbrev: 'Obad', name: 'Obadiah', chapters: 1 },
    { abbrev: 'Jonah', name: 'Jonah', chapters: 4 },
    { abbrev: 'Mic', name: 'Micah', chapters: 7 },
    { abbrev: 'Nah', name: 'Nahum', chapters: 3 },
    { abbrev: 'Hab', name: 'Habakkuk', chapters: 3 },
    { abbrev: 'Zeph', name: 'Zephaniah', chapters: 3 },
    { abbrev: 'Hag', name: 'Haggai', chapters: 2 },
    { abbrev: 'Zech', name: 'Zechariah', chapters: 14 },
    { abbrev: 'Mal', name: 'Malachi', chapters: 4 },
    // New Testament
    { abbrev: 'Matt', name: 'Matthew', chapters: 28 },
    { abbrev: 'Mark', name: 'Mark', chapters: 16 },
    { abbrev: 'Luke', name: 'Luke', chapters: 24 },
    { abbrev: 'John', name: 'John', chapters: 21 },
    { abbrev: 'Acts', name: 'Acts', chapters: 28 },
    { abbrev: 'Rom', name: 'Romans', chapters: 16 },
    { abbrev: '1Cor', name: '1 Corinthians', chapters: 16 },
    { abbrev: '2Cor', name: '2 Corinthians', chapters: 13 },
    { abbrev: 'Gal', name: 'Galatians', chapters: 6 },
    { abbrev: 'Eph', name: 'Ephesians', chapters: 6 },
    { abbrev: 'Phil', name: 'Philippians', chapters: 4 },
    { abbrev: 'Col', name: 'Colossians', chapters: 4 },
    { abbrev: '1Thess', name: '1 Thessalonians', chapters: 5 },
    { abbrev: '2Thess', name: '2 Thessalonians', chapters: 3 },
    { abbrev: '1Tim', name: '1 Timothy', chapters: 6 },
    { abbrev: '2Tim', name: '2 Timothy', chapters: 4 },
    { abbrev: 'Titus', name: 'Titus', chapters: 3 },
    { abbrev: 'Phlm', name: 'Philemon', chapters: 1 },
    { abbrev: 'Heb', name: 'Hebrews', chapters: 13 },
    { abbrev: 'Jas', name: 'James', chapters: 5 },
    { abbrev: '1Pet', name: '1 Peter', chapters: 5 },
    { abbrev: '2Pet', name: '2 Peter', chapters: 3 },
    { abbrev: '1John', name: '1 John', chapters: 5 },
    { abbrev: '2John', name: '2 John', chapters: 1 },
    { abbrev: '3John', name: '3 John', chapters: 1 },
    { abbrev: 'Jude', name: 'Jude', chapters: 1 },
    { abbrev: 'Rev', name: 'Revelation', chapters: 22 },
  ],
  ja: [
    { abbrev: '創', name: '創世記', chapters: 50 },
    { abbrev: '出', name: '出エジプト記', chapters: 40 },
    { abbrev: 'レビ', name: 'レビ記', chapters: 27 },
    { abbrev: '民', name: '民数記', chapters: 36 },
    { abbrev: '申', name: '申命記', chapters: 34 },
    { abbrev: 'ヨシュ', name: 'ヨシュア記', chapters: 24 },
    { abbrev: '士', name: '士師記', chapters: 21 },
    { abbrev: 'ルツ', name: 'ルツ記', chapters: 4 },
    { abbrev: 'Iサム', name: 'サムエル記 上', chapters: 31 },
    { abbrev: 'IIサム', name: 'サムエル記 下', chapters: 24 },
    { abbrev: 'I列', name: '列王記 上', chapters: 22 },
    { abbrev: 'II列', name: '列王記 下', chapters: 25 },
    { abbrev: 'I歴', name: '歴代誌 上', chapters: 29 },
    { abbrev: 'II歴', name: '歴代誌 下', chapters: 36 },
    { abbrev: 'エズ', name: 'エズラ記', chapters: 10 },
    { abbrev: 'ネヘ', name: 'ネヘミヤ記', chapters: 13 },
    { abbrev: 'エス', name: 'エステル記', chapters: 10 },
    { abbrev: 'ヨブ', name: 'ヨブ記', chapters: 42 },
    { abbrev: '詩', name: '詩篇', chapters: 150 },
    { abbrev: '箴', name: '箴言', chapters: 31 },
    { abbrev: '伝', name: '伝道者の書', chapters: 12 },
    { abbrev: '雅', name: '雅歌', chapters: 8 },
    { abbrev: 'イザ', name: 'イザヤ書', chapters: 66 },
    { abbrev: 'エレ', name: 'エレミヤ書', chapters: 52 },
    { abbrev: '哀', name: '哀歌', chapters: 5 },
    { abbrev: 'エゼ', name: 'エゼキエル書', chapters: 48 },
    { abbrev: 'ダニ', name: 'ダニエル書', chapters: 12 },
    { abbrev: 'ホセ', name: 'ホセア書', chapters: 14 },
    { abbrev: 'ヨエ', name: 'ヨエル書', chapters: 3 },
    { abbrev: 'アモ', name: 'アモス書', chapters: 9 },
    { abbrev: 'オバ', name: 'オバデヤ書', chapters: 1 },
    { abbrev: 'ヨナ', name: 'ヨナ書', chapters: 4 },
    { abbrev: 'ミカ', name: 'ミカ書', chapters: 7 },
    { abbrev: 'ナホ', name: 'ナホム書', chapters: 3 },
    { abbrev: 'ハバ', name: 'ハバクク書', chapters: 3 },
    { abbrev: 'ゼパ', name: 'ゼパニヤ書', chapters: 3 },
    { abbrev: 'ハガ', name: 'ハガイ書', chapters: 2 },
    { abbrev: 'ゼカ', name: 'ゼカリヤ書', chapters: 14 },
    { abbrev: 'マラ', name: 'マラキ書', chapters: 4 },
    { abbrev: 'マタ', name: 'マタイの福音書', chapters: 28 },
    { abbrev: 'マル', name: 'マルコの福音書', chapters: 16 },
    { abbrev: 'ルカ', name: 'ルカの福音書', chapters: 24 },
    { abbrev: 'ヨハ', name: 'ヨハネの福音書', chapters: 21 },
    { abbrev: '使', name: '使徒の働き', chapters: 28 },
    { abbrev: 'ロマ', name: 'ローマ人への手紙', chapters: 16 },
    { abbrev: 'Iコリ', name: 'コリント人への手紙 第一', chapters: 16 },
    { abbrev: 'IIコリ', name: 'コリント人への手紙 第二', chapters: 13 },
    { abbrev: 'ガラ', name: 'ガラテヤ人への手紙', chapters: 6 },
    { abbrev: 'エペ', name: 'エペソ人への手紙', chapters: 6 },
    { abbrev: 'ピリ', name: 'ピリピ人への手紙', chapters: 4 },
    { abbrev: 'コロ', name: 'コロサイ人への手紙', chapters: 4 },
    { abbrev: 'Iテサ', name: 'テサロニケ人への手紙 第一', chapters: 5 },
    { abbrev: 'IIテサ', name: 'テサロニケ人への手紙 第二', chapters: 3 },
    { abbrev: 'Iテモ', name: 'テモテへの手紙 第一', chapters: 6 },
    { abbrev: 'IIテモ', name: 'テモテへの手紙 第二', chapters: 4 },
    { abbrev: 'テト', name: 'テトスへの手紙', chapters: 3 },
    { abbrev: 'ピレ', name: 'ピレモンへの手紙', chapters: 1 },
    { abbrev: 'ヘブ', name: 'ヘブル人への手紙', chapters: 13 },
    { abbrev: 'ヤコ', name: 'ヤコブの手紙', chapters: 5 },
    { abbrev: 'Iペテ', name: 'ペテロの手紙 第一', chapters: 5 },
    { abbrev: 'IIペテ', name: 'ペテロの手紙 第二', chapters: 3 },
    { abbrev: 'Iヨハ', name: 'ヨハネの手紙 第一', chapters: 5 },
    { abbrev: 'IIヨハ', name: 'ヨハネの手紙 第二', chapters: 1 },
    { abbrev: 'IIIヨハ', name: 'ヨハネの手紙 第三', chapters: 1 },
    { abbrev: 'ユダ', name: 'ユダの手紙', chapters: 1 },
    { abbrev: '黙', name: 'ヨハネの黙示録', chapters: 22 },
  ],
  es: [
    { abbrev: 'Gén', name: 'Génesis', chapters: 50 },
    { abbrev: 'Éxo', name: 'Éxodo', chapters: 40 },
    { abbrev: 'Lev', name: 'Levítico', chapters: 27 },
    { abbrev: 'Núm', name: 'Números', chapters: 36 },
    { abbrev: 'Deut', name: 'Deuteronomio', chapters: 34 },
    { abbrev: 'Jos', name: 'Josué', chapters: 24 },
    { abbrev: 'Jue', name: 'Jueces', chapters: 21 },
    { abbrev: 'Rut', name: 'Rut', chapters: 4 },
    { abbrev: '1Sam', name: '1 Samuel', chapters: 31 },
    { abbrev: '2Sam', name: '2 Samuel', chapters: 24 },
    { abbrev: '1Rey', name: '1 Reyes', chapters: 22 },
    { abbrev: '2Rey', name: '2 Reyes', chapters: 25 },
    { abbrev: '1Cró', name: '1 Crónicas', chapters: 29 },
    { abbrev: '2Cró', name: '2 Crónicas', chapters: 36 },
    { abbrev: 'Esd', name: 'Esdras', chapters: 10 },
    { abbrev: 'Neh', name: 'Nehemías', chapters: 13 },
    { abbrev: 'Est', name: 'Ester', chapters: 10 },
    { abbrev: 'Job', name: 'Job', chapters: 42 },
    { abbrev: 'Sal', name: 'Salmos', chapters: 150 },
    { abbrev: 'Prov', name: 'Proverbios', chapters: 31 },
    { abbrev: 'Ecl', name: 'Eclesiastés', chapters: 12 },
    { abbrev: 'Cant', name: 'Cantares', chapters: 8 },
    { abbrev: 'Isa', name: 'Isaías', chapters: 66 },
    { abbrev: 'Jer', name: 'Jeremías', chapters: 52 },
    { abbrev: 'Lam', name: 'Lamentaciones', chapters: 5 },
    { abbrev: 'Eze', name: 'Ezequiel', chapters: 48 },
    { abbrev: 'Dan', name: 'Daniel', chapters: 12 },
    { abbrev: 'Ose', name: 'Oseas', chapters: 14 },
    { abbrev: 'Joel', name: 'Joel', chapters: 3 },
    { abbrev: 'Amós', name: 'Amós', chapters: 9 },
    { abbrev: 'Abd', name: 'Abdías', chapters: 1 },
    { abbrev: 'Jon', name: 'Jonás', chapters: 4 },
    { abbrev: 'Miq', name: 'Miqueas', chapters: 7 },
    { abbrev: 'Nah', name: 'Nahúm', chapters: 3 },
    { abbrev: 'Hab', name: 'Habacuc', chapters: 3 },
    { abbrev: 'Sof', name: 'Sofonías', chapters: 3 },
    { abbrev: 'Hag', name: 'Hageo', chapters: 2 },
    { abbrev: 'Zac', name: 'Zacarías', chapters: 14 },
    { abbrev: 'Mal', name: 'Malaquías', chapters: 4 },
    { abbrev: 'Mat', name: 'Mateo', chapters: 28 },
    { abbrev: 'Mar', name: 'Marcos', chapters: 16 },
    { abbrev: 'Luc', name: 'Lucas', chapters: 24 },
    { abbrev: 'Juan', name: 'Juan', chapters: 21 },
    { abbrev: 'Hch', name: 'Hechos', chapters: 28 },
    { abbrev: 'Rom', name: 'Romanos', chapters: 16 },
    { abbrev: '1Cor', name: '1 Corintios', chapters: 16 },
    { abbrev: '2Cor', name: '2 Corintios', chapters: 13 },
    { abbrev: 'Gál', name: 'Gálatas', chapters: 6 },
    { abbrev: 'Efe', name: 'Efesios', chapters: 6 },
    { abbrev: 'Fil', name: 'Filipenses', chapters: 4 },
    { abbrev: 'Col', name: 'Colosenses', chapters: 4 },
    { abbrev: '1Tes', name: '1 Tesalonicenses', chapters: 5 },
    { abbrev: '2Tes', name: '2 Tesalonicenses', chapters: 3 },
    { abbrev: '1Tim', name: '1 Timoteo', chapters: 6 },
    { abbrev: '2Tim', name: '2 Timoteo', chapters: 4 },
    { abbrev: 'Tit', name: 'Tito', chapters: 3 },
    { abbrev: 'Flm', name: 'Filemón', chapters: 1 },
    { abbrev: 'Heb', name: 'Hebreos', chapters: 13 },
    { abbrev: 'Sant', name: 'Santiago', chapters: 5 },
    { abbrev: '1Ped', name: '1 Pedro', chapters: 5 },
    { abbrev: '2Ped', name: '2 Pedro', chapters: 3 },
    { abbrev: '1Jn', name: '1 Juan', chapters: 5 },
    { abbrev: '2Jn', name: '2 Juan', chapters: 1 },
    { abbrev: '3Jn', name: '3 Juan', chapters: 1 },
    { abbrev: 'Jud', name: 'Judas', chapters: 1 },
    { abbrev: 'Apoc', name: 'Apocalipsis', chapters: 22 },
  ],
} as const;

// ============================================================================
// SLIDE DEFAULTS
// ============================================================================

export const DEFAULT_SLIDE_BACKGROUND: import('../types').SlideBackground = {
  type: 'color',
  value: '#1a1a2e',
  opacity: 1,
};

export const DEFAULT_TRANSITION: import('../types').SlideTransition = {
  type: 'fade',
  duration: 300,
};

// ============================================================================
// UI CONSTANTS
// ============================================================================

export const KEYBOARD_SHORTCUTS = {
  commandPalette: { key: 'k', meta: true },
  newSlide: { key: 'n', meta: true },
  deleteSlide: { key: 'Backspace', meta: true },
  duplicateSlide: { key: 'd', meta: true, shift: true },
  present: { key: 'p', meta: true, shift: true },
  save: { key: 's', meta: true },
  undo: { key: 'z', meta: true },
  redo: { key: 'z', meta: true, shift: true },
  nextSlide: { key: 'ArrowRight' },
  prevSlide: { key: 'ArrowLeft' },
  search: { key: 'f', meta: true },
  bibleSearch: { key: 'b', meta: true },
} as const;
