import { internalAction } from "./_generated/server";
import { internal } from "./_generated/api";

// Bible book data
const BIBLE_BOOKS = [
  { num: 1, name: "Genesis", short: "Gen", testament: "old" as const, chapters: 50 },
  { num: 2, name: "Exodus", short: "Exod", testament: "old" as const, chapters: 40 },
  { num: 3, name: "Leviticus", short: "Lev", testament: "old" as const, chapters: 27 },
  { num: 4, name: "Numbers", short: "Num", testament: "old" as const, chapters: 36 },
  { num: 5, name: "Deuteronomy", short: "Deut", testament: "old" as const, chapters: 34 },
  { num: 6, name: "Joshua", short: "Josh", testament: "old" as const, chapters: 24 },
  { num: 7, name: "Judges", short: "Judg", testament: "old" as const, chapters: 21 },
  { num: 8, name: "Ruth", short: "Ruth", testament: "old" as const, chapters: 4 },
  { num: 9, name: "1 Samuel", short: "1Sam", testament: "old" as const, chapters: 31 },
  { num: 10, name: "2 Samuel", short: "2Sam", testament: "old" as const, chapters: 24 },
  { num: 11, name: "1 Kings", short: "1Kgs", testament: "old" as const, chapters: 22 },
  { num: 12, name: "2 Kings", short: "2Kgs", testament: "old" as const, chapters: 25 },
  { num: 13, name: "1 Chronicles", short: "1Chr", testament: "old" as const, chapters: 29 },
  { num: 14, name: "2 Chronicles", short: "2Chr", testament: "old" as const, chapters: 36 },
  { num: 15, name: "Ezra", short: "Ezra", testament: "old" as const, chapters: 10 },
  { num: 16, name: "Nehemiah", short: "Neh", testament: "old" as const, chapters: 13 },
  { num: 17, name: "Esther", short: "Esth", testament: "old" as const, chapters: 10 },
  { num: 18, name: "Job", short: "Job", testament: "old" as const, chapters: 42 },
  { num: 19, name: "Psalms", short: "Ps", testament: "old" as const, chapters: 150 },
  { num: 20, name: "Proverbs", short: "Prov", testament: "old" as const, chapters: 31 },
  { num: 21, name: "Ecclesiastes", short: "Eccl", testament: "old" as const, chapters: 12 },
  { num: 22, name: "Song of Solomon", short: "Song", testament: "old" as const, chapters: 8 },
  { num: 23, name: "Isaiah", short: "Isa", testament: "old" as const, chapters: 66 },
  { num: 24, name: "Jeremiah", short: "Jer", testament: "old" as const, chapters: 52 },
  { num: 25, name: "Lamentations", short: "Lam", testament: "old" as const, chapters: 5 },
  { num: 26, name: "Ezekiel", short: "Ezek", testament: "old" as const, chapters: 48 },
  { num: 27, name: "Daniel", short: "Dan", testament: "old" as const, chapters: 12 },
  { num: 28, name: "Hosea", short: "Hos", testament: "old" as const, chapters: 14 },
  { num: 29, name: "Joel", short: "Joel", testament: "old" as const, chapters: 3 },
  { num: 30, name: "Amos", short: "Amos", testament: "old" as const, chapters: 9 },
  { num: 31, name: "Obadiah", short: "Obad", testament: "old" as const, chapters: 1 },
  { num: 32, name: "Jonah", short: "Jonah", testament: "old" as const, chapters: 4 },
  { num: 33, name: "Micah", short: "Mic", testament: "old" as const, chapters: 7 },
  { num: 34, name: "Nahum", short: "Nah", testament: "old" as const, chapters: 3 },
  { num: 35, name: "Habakkuk", short: "Hab", testament: "old" as const, chapters: 3 },
  { num: 36, name: "Zephaniah", short: "Zeph", testament: "old" as const, chapters: 3 },
  { num: 37, name: "Haggai", short: "Hag", testament: "old" as const, chapters: 2 },
  { num: 38, name: "Zechariah", short: "Zech", testament: "old" as const, chapters: 14 },
  { num: 39, name: "Malachi", short: "Mal", testament: "old" as const, chapters: 4 },
  { num: 40, name: "Matthew", short: "Matt", testament: "new" as const, chapters: 28 },
  { num: 41, name: "Mark", short: "Mark", testament: "new" as const, chapters: 16 },
  { num: 42, name: "Luke", short: "Luke", testament: "new" as const, chapters: 24 },
  { num: 43, name: "John", short: "John", testament: "new" as const, chapters: 21 },
  { num: 44, name: "Acts", short: "Acts", testament: "new" as const, chapters: 28 },
  { num: 45, name: "Romans", short: "Rom", testament: "new" as const, chapters: 16 },
  { num: 46, name: "1 Corinthians", short: "1Cor", testament: "new" as const, chapters: 16 },
  { num: 47, name: "2 Corinthians", short: "2Cor", testament: "new" as const, chapters: 13 },
  { num: 48, name: "Galatians", short: "Gal", testament: "new" as const, chapters: 6 },
  { num: 49, name: "Ephesians", short: "Eph", testament: "new" as const, chapters: 6 },
  { num: 50, name: "Philippians", short: "Phil", testament: "new" as const, chapters: 4 },
  { num: 51, name: "Colossians", short: "Col", testament: "new" as const, chapters: 4 },
  { num: 52, name: "1 Thessalonians", short: "1Thess", testament: "new" as const, chapters: 5 },
  { num: 53, name: "2 Thessalonians", short: "2Thess", testament: "new" as const, chapters: 3 },
  { num: 54, name: "1 Timothy", short: "1Tim", testament: "new" as const, chapters: 6 },
  { num: 55, name: "2 Timothy", short: "2Tim", testament: "new" as const, chapters: 4 },
  { num: 56, name: "Titus", short: "Titus", testament: "new" as const, chapters: 3 },
  { num: 57, name: "Philemon", short: "Phlm", testament: "new" as const, chapters: 1 },
  { num: 58, name: "Hebrews", short: "Heb", testament: "new" as const, chapters: 13 },
  { num: 59, name: "James", short: "Jas", testament: "new" as const, chapters: 5 },
  { num: 60, name: "1 Peter", short: "1Pet", testament: "new" as const, chapters: 5 },
  { num: 61, name: "2 Peter", short: "2Pet", testament: "new" as const, chapters: 3 },
  { num: 62, name: "1 John", short: "1John", testament: "new" as const, chapters: 5 },
  { num: 63, name: "2 John", short: "2John", testament: "new" as const, chapters: 1 },
  { num: 64, name: "3 John", short: "3John", testament: "new" as const, chapters: 1 },
  { num: 65, name: "Jude", short: "Jude", testament: "new" as const, chapters: 1 },
  { num: 66, name: "Revelation", short: "Rev", testament: "new" as const, chapters: 22 },
];

// Bible versions to seed
const BIBLE_VERSIONS = [
  { code: "kjv", name: "King James Version", language: "en", copyright: "Public Domain", bookCount: 66, verseCount: 31102 },
  { code: "asv", name: "American Standard Version", language: "en", copyright: "Public Domain", bookCount: 66, verseCount: 31102 },
  { code: "bbe", name: "Bible in Basic English", language: "en", copyright: "Public Domain", bookCount: 66, verseCount: 31102 },
  { code: "rvr1909", name: "Reina-Valera 1909", language: "es", copyright: "Public Domain", bookCount: 66, verseCount: 31102 },
  { code: "rvr1865", name: "Reina-Valera 1865", language: "es", copyright: "Public Domain", bookCount: 66, verseCount: 31102 },
  { code: "japkougo", name: "口語訳聖書 (Kougo-yaku)", language: "ja", copyright: "Public Domain", bookCount: 66, verseCount: 31102 },
  { code: "japbungo", name: "明治元訳/大正改訳 (Bungo)", language: "ja", copyright: "Public Domain", bookCount: 66, verseCount: 31102 },
];

// Top worship songs - English
const ENGLISH_SONGS = [
  { title: "How Great Is Our God", artist: "Chris Tomlin", tempo: "Medium", key: "C" },
  { title: "10,000 Reasons (Bless the Lord)", artist: "Matt Redman", tempo: "Medium", key: "G" },
  { title: "What A Beautiful Name", artist: "Hillsong Worship", tempo: "Slow", key: "D" },
  { title: "Good Good Father", artist: "Chris Tomlin", tempo: "Medium", key: "G" },
  { title: "Reckless Love", artist: "Cory Asbury", tempo: "Medium", key: "C" },
  { title: "Amazing Grace (My Chains Are Gone)", artist: "Chris Tomlin", tempo: "Medium", key: "G" },
  { title: "Oceans (Where Feet May Fail)", artist: "Hillsong United", tempo: "Slow", key: "D" },
  { title: "Great Are You Lord", artist: "All Sons & Daughters", tempo: "Slow", key: "G" },
  { title: "Build My Life", artist: "Housefires", tempo: "Medium", key: "E" },
  { title: "Way Maker", artist: "Sinach", tempo: "Medium", key: "E" },
  { title: "King of Kings", artist: "Hillsong Worship", tempo: "Medium", key: "D" },
  { title: "Goodness of God", artist: "Bethel Music", tempo: "Medium", key: "G" },
  { title: "Living Hope", artist: "Phil Wickham", tempo: "Medium", key: "C" },
  { title: "The Blessing", artist: "Kari Jobe & Cody Carnes", tempo: "Slow", key: "Eb" },
  { title: "Who You Say I Am", artist: "Hillsong Worship", tempo: "Medium", key: "C" },
  { title: "Graves Into Gardens", artist: "Elevation Worship", tempo: "Medium", key: "G" },
  { title: "Cornerstone", artist: "Hillsong Worship", tempo: "Medium", key: "C" },
  { title: "Here I Am To Worship", artist: "Tim Hughes", tempo: "Medium", key: "D" },
  { title: "This Is Amazing Grace", artist: "Phil Wickham", tempo: "Fast", key: "G" },
  { title: "Holy Spirit", artist: "Francesca Battistelli", tempo: "Slow", key: "E" },
  { title: "Revelation Song", artist: "Kari Jobe", tempo: "Slow", key: "D" },
  { title: "How Great Thou Art", artist: "Traditional", tempo: "Medium", key: "Bb" },
  { title: "Blessed Be Your Name", artist: "Matt Redman", tempo: "Fast", key: "A" },
  { title: "Forever", artist: "Chris Tomlin", tempo: "Fast", key: "G" },
  { title: "Mighty To Save", artist: "Hillsong Worship", tempo: "Medium", key: "A" },
  { title: "Our God", artist: "Chris Tomlin", tempo: "Fast", key: "Em" },
  { title: "Jesus Messiah", artist: "Chris Tomlin", tempo: "Medium", key: "A" },
  { title: "In Christ Alone", artist: "Keith & Kristyn Getty", tempo: "Medium", key: "D" },
  { title: "Open The Eyes Of My Heart", artist: "Paul Baloche", tempo: "Fast", key: "E" },
  { title: "Everlasting God", artist: "Lincoln Brewster", tempo: "Fast", key: "Bb" },
  { title: "Trading My Sorrows", artist: "Darrell Evans", tempo: "Fast", key: "G" },
  { title: "Shout To The Lord", artist: "Darlene Zschech", tempo: "Medium", key: "Bb" },
  { title: "Lord I Lift Your Name On High", artist: "Rick Founds", tempo: "Fast", key: "G" },
  { title: "As The Deer", artist: "Martin Nystrom", tempo: "Slow", key: "D" },
  { title: "Come Now Is The Time To Worship", artist: "Brian Doerksen", tempo: "Medium", key: "D" },
  { title: "Days of Elijah", artist: "Robin Mark", tempo: "Fast", key: "G" },
  { title: "You Are My King (Amazing Love)", artist: "Newsboys", tempo: "Medium", key: "D" },
  { title: "Your Grace Is Enough", artist: "Matt Maher", tempo: "Medium", key: "G" },
  { title: "I Could Sing Of Your Love Forever", artist: "Delirious?", tempo: "Medium", key: "E" },
  { title: "Better Is One Day", artist: "Matt Redman", tempo: "Medium", key: "E" },
  { title: "Hosanna", artist: "Hillsong Worship", tempo: "Medium", key: "Eb" },
  { title: "You Are My All In All", artist: "Dennis Jernigan", tempo: "Medium", key: "F" },
  { title: "I Will Follow", artist: "Chris Tomlin", tempo: "Fast", key: "E" },
  { title: "Glorious Day", artist: "Casting Crowns", tempo: "Medium", key: "G" },
  { title: "No Longer Slaves", artist: "Bethel Music", tempo: "Medium", key: "A" },
  { title: "Raise A Hallelujah", artist: "Bethel Music", tempo: "Fast", key: "A" },
  { title: "The Heart of Worship", artist: "Matt Redman", tempo: "Slow", key: "D" },
  { title: "Great I Am", artist: "Phillips Craig & Dean", tempo: "Medium", key: "Bb" },
  { title: "Lord I Need You", artist: "Matt Maher", tempo: "Slow", key: "G" },
  { title: "Indescribable", artist: "Chris Tomlin", tempo: "Medium", key: "Bb" },
];

// Top worship songs - Spanish
const SPANISH_SONGS = [
  { title: "Cuán Grande Es Dios", artist: "Hillsong en Español", tempo: "Medium", key: "C" },
  { title: "Gracia Sublime", artist: "Christine D'Clario", tempo: "Medium", key: "G" },
  { title: "Al Que Es Digno", artist: "Marcos Witt", tempo: "Medium", key: "D" },
  { title: "Tu Fidelidad", artist: "Marcos Witt", tempo: "Slow", key: "G" },
  { title: "Renuévame", artist: "Marcos Witt", tempo: "Slow", key: "D" },
  { title: "Te Amo", artist: "Israel Houghton", tempo: "Medium", key: "G" },
  { title: "Eres Mi Respirar", artist: "Hillsong en Español", tempo: "Slow", key: "E" },
  { title: "Abre Mis Ojos", artist: "Danilo Montero", tempo: "Slow", key: "D" },
  { title: "Tu Eres Mi Pastor", artist: "Danilo Montero", tempo: "Slow", key: "G" },
  { title: "Poderoso Dios", artist: "Generación 12", tempo: "Fast", key: "A" },
  { title: "Grande Y Fuerte", artist: "Miel San Marcos", tempo: "Medium", key: "E" },
  { title: "Sobrenatural", artist: "Miel San Marcos", tempo: "Fast", key: "A" },
  { title: "Algo Está Cayendo Aquí", artist: "Miel San Marcos", tempo: "Fast", key: "G" },
  { title: "Santo", artist: "Marco Barrientos", tempo: "Slow", key: "D" },
  { title: "Avívanos", artist: "Marco Barrientos", tempo: "Medium", key: "G" },
  { title: "Tu Mirada", artist: "Marco Barrientos", tempo: "Slow", key: "E" },
  { title: "Digno Es El Señor", artist: "Danilo Montero", tempo: "Fast", key: "G" },
  { title: "Eres Todopoderoso", artist: "Generación 12", tempo: "Medium", key: "A" },
  { title: "Majestuoso", artist: "Christine D'Clario", tempo: "Medium", key: "D" },
  { title: "Padre Nuestro", artist: "Christine D'Clario", tempo: "Slow", key: "G" },
  { title: "Mi Corazón", artist: "Jesús Adrián Romero", tempo: "Slow", key: "E" },
  { title: "Supe Que Me Amabas", artist: "Marcela Gándara", tempo: "Slow", key: "G" },
  { title: "Un Día A La Vez", artist: "Tercer Cielo", tempo: "Slow", key: "C" },
  { title: "Dios Incomparable", artist: "Generación 12", tempo: "Fast", key: "G" },
  { title: "Grande Es Tu Amor", artist: "En Espíritu Y En Verdad", tempo: "Medium", key: "D" },
  { title: "Alaba", artist: "Marcos Witt", tempo: "Fast", key: "G" },
  { title: "Yo Te Busco", artist: "Marcos Witt", tempo: "Slow", key: "E" },
  { title: "Dios Está Aquí", artist: "Danilo Montero", tempo: "Medium", key: "D" },
  { title: "Él Me Levantará", artist: "Miel San Marcos", tempo: "Medium", key: "G" },
  { title: "Ven", artist: "Miel San Marcos", tempo: "Fast", key: "A" },
  { title: "Me Rindo A Ti", artist: "Hillsong en Español", tempo: "Slow", key: "C" },
  { title: "Océanos", artist: "Hillsong en Español", tempo: "Slow", key: "D" },
  { title: "Cristo Te Ama", artist: "Tercer Cielo", tempo: "Medium", key: "G" },
  { title: "Tu Nombre", artist: "Christine D'Clario", tempo: "Medium", key: "E" },
  { title: "Hermoso Nombre", artist: "Hillsong en Español", tempo: "Slow", key: "D" },
  { title: "Rey de Reyes", artist: "Hillsong en Español", tempo: "Medium", key: "D" },
  { title: "Aquí Estoy", artist: "Jesús Adrián Romero", tempo: "Slow", key: "G" },
  { title: "Levanto Mis Manos", artist: "Samuel Hernández", tempo: "Slow", key: "Eb" },
  { title: "No Hay Otro Nombre", artist: "Hillsong en Español", tempo: "Medium", key: "A" },
  { title: "Eres", artist: "Barak", tempo: "Medium", key: "G" },
  { title: "Toma Tu Lugar", artist: "Hillsong en Español", tempo: "Slow", key: "E" },
  { title: "Hosanna (Hillsong)", artist: "Hillsong en Español", tempo: "Medium", key: "Eb" },
  { title: "Más Que Vencedores", artist: "Marco Barrientos", tempo: "Fast", key: "G" },
  { title: "Sólo Tú", artist: "Jesús Adrián Romero", tempo: "Slow", key: "D" },
  { title: "Creo En Ti", artist: "Tercer Cielo", tempo: "Slow", key: "G" },
  { title: "Tu Sangre", artist: "Miel San Marcos", tempo: "Fast", key: "A" },
  { title: "Que Se Abra El Cielo", artist: "Christine D'Clario", tempo: "Medium", key: "E" },
  { title: "Señor Te Necesito", artist: "Marcos Witt", tempo: "Slow", key: "D" },
  { title: "Amor Sin Condición", artist: "Danilo Montero", tempo: "Slow", key: "G" },
  { title: "Mi Dios Es Bueno", artist: "Miel San Marcos", tempo: "Fast", key: "G" },
];

// Top worship songs - Japanese
const JAPANESE_SONGS = [
  { title: "偉大な神 (How Great Is Our God)", artist: "Hillsong Japan", tempo: "Medium", key: "C" },
  { title: "主は良いお方 (Goodness of God)", artist: "Hillsong Japan", tempo: "Medium", key: "G" },
  { title: "Way Maker", artist: "Japanese Worship", tempo: "Medium", key: "E" },
  { title: "美しい御名 (What A Beautiful Name)", artist: "Hillsong Japan", tempo: "Slow", key: "D" },
  { title: "主の愛 (Lord's Love)", artist: "久保田純子", tempo: "Slow", key: "G" },
  { title: "聖なる聖なる (Holy Holy Holy)", artist: "Traditional Japanese", tempo: "Medium", key: "D" },
  { title: "主は我が力 (The Lord Is My Strength)", artist: "久米小百合", tempo: "Medium", key: "G" },
  { title: "イエスが愛したように (As Jesus Loved)", artist: "小坂忠", tempo: "Slow", key: "C" },
  { title: "天の神 (God of Heaven)", artist: "Jesus Lifehouse", tempo: "Medium", key: "D" },
  { title: "感謝します (I Give Thanks)", artist: "小坂忠", tempo: "Slow", key: "G" },
  { title: "主を賛美しよう (Let's Praise the Lord)", artist: "Traditional", tempo: "Fast", key: "G" },
  { title: "驚くばかりの恵み (Amazing Grace)", artist: "Traditional Japanese", tempo: "Medium", key: "G" },
  { title: "主イエスの愛 (The Love of Jesus)", artist: "Hillsong Japan", tempo: "Medium", key: "D" },
  { title: "新しい朝 (New Morning)", artist: "久米小百合", tempo: "Medium", key: "E" },
  { title: "主の祈り (The Lord's Prayer)", artist: "Traditional", tempo: "Slow", key: "C" },
  { title: "御手の中で (In Your Hands)", artist: "Japanese Worship", tempo: "Slow", key: "G" },
  { title: "私の望み (My Hope)", artist: "Hillsong Japan", tempo: "Medium", key: "D" },
  { title: "輝く日を仰ぐとき (When I Behold the Shining Day)", artist: "Traditional", tempo: "Medium", key: "Bb" },
  { title: "神の御子イエス (Jesus Son of God)", artist: "Traditional", tempo: "Medium", key: "G" },
  { title: "主よ人の望みの喜びよ (Jesu, Joy of Man's Desiring)", artist: "J.S. Bach", tempo: "Slow", key: "G" },
  { title: "栄光の主 (Glorious Lord)", artist: "Jesus Lifehouse", tempo: "Medium", key: "A" },
  { title: "永遠の神 (Eternal God)", artist: "Hillsong Japan", tempo: "Slow", key: "E" },
  { title: "愛する主よ (Beloved Lord)", artist: "Japanese Worship", tempo: "Slow", key: "D" },
  { title: "御言葉の光 (Light of Your Word)", artist: "久保田純子", tempo: "Medium", key: "G" },
  { title: "主に感謝せよ (Give Thanks to the Lord)", artist: "Traditional", tempo: "Fast", key: "D" },
  { title: "救い主 (Savior)", artist: "Jesus Lifehouse", tempo: "Medium", key: "C" },
  { title: "主のみことば (Word of the Lord)", artist: "Japanese Worship", tempo: "Medium", key: "G" },
  { title: "十字架の愛 (Love of the Cross)", artist: "小坂忠", tempo: "Slow", key: "D" },
  { title: "信じます (I Believe)", artist: "Hillsong Japan", tempo: "Medium", key: "E" },
  { title: "聖霊の風 (Wind of the Spirit)", artist: "Japanese Worship", tempo: "Medium", key: "G" },
  { title: "今日も主と共に (With the Lord Today)", artist: "久米小百合", tempo: "Medium", key: "D" },
  { title: "わが主の愛 (Love of My Lord)", artist: "Traditional", tempo: "Slow", key: "G" },
  { title: "主よ来てください (Lord Come)", artist: "Jesus Lifehouse", tempo: "Slow", key: "A" },
  { title: "平和の君 (Prince of Peace)", artist: "Hillsong Japan", tempo: "Medium", key: "E" },
  { title: "賛美の歌声 (Voice of Praise)", artist: "Japanese Worship", tempo: "Fast", key: "G" },
  { title: "主を仰ぎ見れば (Looking Up to the Lord)", artist: "Traditional", tempo: "Slow", key: "D" },
  { title: "ハレルヤ (Hallelujah)", artist: "Japanese Worship", tempo: "Fast", key: "G" },
  { title: "神様の愛 (God's Love)", artist: "久保田純子", tempo: "Slow", key: "C" },
  { title: "いつくしみ深い (What a Friend We Have)", artist: "Traditional", tempo: "Medium", key: "F" },
  { title: "主の道を歩む (Walking in the Lord's Way)", artist: "小坂忠", tempo: "Medium", key: "G" },
  { title: "力の源 (Source of Power)", artist: "Jesus Lifehouse", tempo: "Fast", key: "A" },
  { title: "主よ御手もて (Lord with Your Hand)", artist: "Traditional", tempo: "Slow", key: "D" },
  { title: "朝ごとに (Every Morning)", artist: "Japanese Worship", tempo: "Medium", key: "G" },
  { title: "まことの神 (True God)", artist: "Hillsong Japan", tempo: "Medium", key: "E" },
  { title: "天よりの声 (Voice from Heaven)", artist: "Japanese Worship", tempo: "Medium", key: "D" },
  { title: "御霊よ来たれ (Spirit Come)", artist: "Jesus Lifehouse", tempo: "Slow", key: "G" },
  { title: "光の中に (In the Light)", artist: "久米小百合", tempo: "Medium", key: "A" },
  { title: "主は導く (The Lord Leads)", artist: "Traditional", tempo: "Medium", key: "D" },
  { title: "恵みの主 (Lord of Grace)", artist: "Japanese Worship", tempo: "Slow", key: "G" },
  { title: "祈りの歌 (Song of Prayer)", artist: "小坂忠", tempo: "Slow", key: "E" },
];

// Seed all data
export const seedAllData = internalAction({
  args: {},
  handler: async (ctx) => {
    console.log("Starting seed...");
    
    // Seed Bible versions
    for (const version of BIBLE_VERSIONS) {
      await ctx.runMutation(internal.bible.seedBibleVersion, version);
    }
    console.log("Bible versions seeded");

    // Seed songs
    for (const song of ENGLISH_SONGS) {
      await ctx.runMutation(internal.songs.seedSong, {
        title: song.title,
        artist: song.artist,
        language: "en",
        lyrics: `[Verse 1]\n${song.title} lyrics placeholder\n\n[Chorus]\nChorus placeholder`,
        sections: [
          { type: "verse", label: "Verse 1", lines: [`${song.title} lyrics placeholder`] },
          { type: "chorus", label: "Chorus", lines: ["Chorus placeholder"] },
        ],
        tempo: song.tempo,
        key: song.key,
        tags: ["worship", "english"],
      });
    }
    console.log("English songs seeded");

    for (const song of SPANISH_SONGS) {
      await ctx.runMutation(internal.songs.seedSong, {
        title: song.title,
        artist: song.artist,
        language: "es",
        lyrics: `[Verso 1]\n${song.title} letra placeholder\n\n[Coro]\nCoro placeholder`,
        sections: [
          { type: "verse", label: "Verso 1", lines: [`${song.title} letra placeholder`] },
          { type: "chorus", label: "Coro", lines: ["Coro placeholder"] },
        ],
        tempo: song.tempo,
        key: song.key,
        tags: ["worship", "spanish"],
      });
    }
    console.log("Spanish songs seeded");

    for (const song of JAPANESE_SONGS) {
      await ctx.runMutation(internal.songs.seedSong, {
        title: song.title,
        artist: song.artist,
        language: "ja",
        lyrics: `[1番]\n${song.title} 歌詞プレースホルダー\n\n[サビ]\nサビプレースホルダー`,
        sections: [
          { type: "verse", label: "1番", lines: [`${song.title} 歌詞プレースホルダー`] },
          { type: "chorus", label: "サビ", lines: ["サビプレースホルダー"] },
        ],
        tempo: song.tempo,
        key: song.key,
        tags: ["worship", "japanese"],
      });
    }
    console.log("Japanese songs seeded");

    console.log("Seed complete!");
    return { success: true };
  },
});
